### ISSUE TITLE
set method missing

### ISSUE THREAD

**Issue by iguberman** [andytill/oneup#2]
I believe it would be super useful if `set(Counter, Value)` method was available.  Something silly like `oneup:inc2(Counter, -(oneup:get(Counter)) + Value)` isn't atomic.

**Comment by andytill** [comment]
This would be very useful, the doc to the underlying `std::atomic::store` function is [here](http://en.cppreference.com/w/cpp/atomic/atomic/store)

**Comment by iguberman** [comment]
Cool, thanks so much! I'll take care of it.
